"""Build the readable report for the cross-wiki move mapping, and check it against the product.

    python research/ground_truth/scripts/wiki_mapping_report.py          # rewrite the report
    python research/ground_truth/scripts/wiki_mapping_report.py --check  # only verify, exit 1 on problems

The mapping files (semantic/wiki_mapping/<boss>.json) are the source of truth. The check
fails when a product move in backend/seed/bosses.json is missing from the mapping, mapped
twice, or no longer exists, so the mapping cannot silently drift from the product.
"""

import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
MAPPING_DIR = ROOT / "research" / "ground_truth" / "semantic" / "wiki_mapping"
REPORT = MAPPING_DIR / "README.md"
SEED = ROOT / "backend" / "seed" / "bosses.json"

RELATIONS = {
    "same": "Both wikis describe the same action with the same boundaries.",
    "partial": "Overlapping, but details differ (hit count, follow-ups, conditions).",
    "split": "Divided differently: one entry on one side covers several on the other.",
    "conflict": "The wikis contradict each other.",
    "unclear": "No confident correspondence.",
    "only_fextralife": "Only Fextralife describes it.",
    "only_fandom": "Only Fandom describes it.",
}
V4_STATUSES = {"unverified"}


def load_mappings() -> list[dict]:
    return [json.loads(p.read_text(encoding="utf-8")) for p in sorted(MAPPING_DIR.glob("*.json"))]


def check(mappings: list[dict]) -> list[str]:
    seed = json.loads(SEED.read_text(encoding="utf-8"))
    product = {b["id"]: {m["id"] for p in b["phases"] for m in p["moves"]} for b in seed}
    problems = []
    for boss_id in product.keys() - {m["boss"] for m in mappings}:
        problems.append(f"{boss_id}: no mapping file")
    for mapping in mappings:
        boss_id = mapping["boss"]
        mapped = Counter(move for entry in mapping["entries"] for move in entry["product_moves"])
        for move, count in mapped.items():
            if count > 1:
                problems.append(f"{boss_id}/{move}: mapped {count} times")
        for move in product.get(boss_id, set()) - mapped.keys():
            problems.append(f"{boss_id}/{move}: product move missing from the mapping")
        for move in mapped.keys() - product.get(boss_id, set()):
            problems.append(f"{boss_id}/{move}: mapped but not in the product")
        for entry in mapping["entries"]:
            if entry["relation"] not in RELATIONS:
                problems.append(f"{boss_id}: unknown relation {entry['relation']!r}")
            if entry["v4_status"] not in V4_STATUSES:
                # Anything beyond "unverified" must be decided by the project owner, not by tooling.
                problems.append(f"{boss_id}: unexpected v4_status {entry['v4_status']!r}")
    return problems


def cell(items: list[str]) -> str:
    return "<br>".join(f"`{i}`" if " " not in i and i.islower() else i for i in items) or "—"


def report(mappings: list[dict]) -> str:
    lines = [
        "# Cross-wiki move mapping",
        "",
        "Generated by `research/ground_truth/scripts/wiki_mapping_report.py` from the JSON files in this folder. Do not edit by hand.",
        "",
        "For every boss in the product, each row lines up a product move with the Fextralife and Fandom entries that describe it, "
        "and records how they relate. It measures how much two independent human sources disagree, which is a **lower bound** on the "
        "gap between the product's movesets and engine-level ground truth.",
        "",
        "**Nothing here is ground truth.** Every row is `unverified`. V4 adds runtime and engine evidence to `engine_evidence`; "
        "which semantic moves and mappings become ground truth is decided by the project owner, never by tooling or by Claude.",
        "",
        "## Relations",
        "",
        "| Relation | Meaning |",
        "|---|---|",
        *[f"| `{name}` | {meaning} |" for name, meaning in RELATIONS.items()],
        "",
        "## Summary",
        "",
        "| Boss | Product moves | Rows | same | partial | split | conflict | unclear | only Fextralife | only Fandom | Product moves matched 1:1 |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    totals = Counter()
    for m in mappings:
        rel = Counter(e["relation"] for e in m["entries"])
        product_moves = sum(len(e["product_moves"]) for e in m["entries"])
        matched = sum(len(e["product_moves"]) for e in m["entries"] if e["relation"] == "same")
        totals.update(rel)
        totals["product"] += product_moves
        totals["rows"] += len(m["entries"])
        totals["matched"] += matched
        lines.append(
            f"| {m['boss']} | {product_moves} | {len(m['entries'])} | "
            + " | ".join(str(rel[r]) for r in RELATIONS)
            + f" | {matched}/{product_moves} |"
        )
    lines.append(
        f"| **Total** | **{totals['product']}** | **{totals['rows']}** | "
        + " | ".join(f"**{totals[r]}**" for r in RELATIONS)
        + f" | **{totals['matched']}/{totals['product']}** |"
    )

    for m in mappings:
        fx, fd = m["sources"]["fextralife"], m["sources"]["fandom"]
        lines += [
            "",
            f"## {m['boss']}",
            "",
            f"- Ruleset: {m['ruleset']}. Product data originally from: {m['product_source']}.",
            f"- Fextralife: <{fx['url']}> ({fx['version']}, fetched {fx['fetched']})",
            f"- Fandom: <{fd['url']}> ({fd['version']}, fetched {fd['fetched']})",
            *[f"- {note}" for note in m["notes"]],
            "",
            "| Product moves | Fextralife | Fandom | Relation | Notes |",
            "|---|---|---|---|---|",
        ]
        for e in m["entries"]:
            notes = e["notes"].replace("|", "/") or ""
            lines.append(
                f"| {cell(e['product_moves'])} | {cell(e['fextralife'])} | {cell(e['fandom'])} | `{e['relation']}` | {notes} |"
            )
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    mappings = load_mappings()
    problems = check(mappings)
    for problem in problems:
        print(problem, file=sys.stderr)
    if problems:
        return 1
    if "--check" not in argv:
        REPORT.write_text(report(mappings), encoding="utf-8", newline="\n")
        print(f"wrote {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
